# Schema for the configuration files of the Amrita appraisal module.
amrita_appraisal.settings:
  type: config_object
  label: 'Amrita appraisal settings'
  mapping:
    example:
      type: string
      label: 'Example'
