# Schema for the configuration files of the Amrita index module.
amrita_index.settings:
  type: config_object
  label: 'Amrita index settings'
  mapping:
    example:
      type: string
      label: 'Example'
