# Schema for the configuration files of the Aes settings module.
aes_settings.settings:
  type: config_object
  label: 'Aes settings settings'
  mapping:
    example:
      type: string
      label: 'Example'
