# Schema for the configuration files of the Amrita settings module.
amrita_settings.settings:
  type: config_object
  label: 'Amrita settings settings'
  mapping:
    example:
      type: string
      label: 'Example'
